"""Candidate FULL-SPECTRUM-20 configured ensemble.

All families receive a disposition; execution remains relevance/admissibility driven.
"""
FAMILIES=(
"GOAL_TARGET_FREEZE","DOS_OBSERVE","MTA","MT_MODE_SWEEP","PD","PD_AUDIT",
"MULTI_OBJECT_MOMT","ARCHITECTURE","ROOT_CAUSE","ARA_ARTIFACT_REALITY",
"ORPHAN_GHOST_CONFLICT","CURRENTNESS","ROLE_ASSIGNMENT_OWNER_CLOSURE",
"CONSEQUENCE_AFFECTED_CONE","RTC_RAISE_CEILING","MTOS","TRANSFER_CORE",
"EXECUTION_TRUTH_ACTIVATION","A16_HOLDOUT_ABLATION","GOAL_COMPLETION_CERT"
)
DEFAULT_ORDER=(
"GOAL_TARGET_FREEZE","DOS_OBSERVE","MTA","PD","PD_AUDIT","ARCHITECTURE",
"MT_MODE_SWEEP","MULTI_OBJECT_MOMT","ROOT_CAUSE","ARCHITECTURE",
"ARA_ARTIFACT_REALITY","ORPHAN_GHOST_CONFLICT","CURRENTNESS",
"ROLE_ASSIGNMENT_OWNER_CLOSURE","CONSEQUENCE_AFFECTED_CONE",
"RTC_RAISE_CEILING","MTOS","TRANSFER_CORE","A16_HOLDOUT_ABLATION",
"EXECUTION_TRUTH_ACTIVATION","GOAL_COMPLETION_CERT"
)
def disposition(relevant):
    rel=set(relevant)
    return {f:("SELECT" if f in rel else "NON_APPLICABLE") for f in FAMILIES}
