#!/usr/bin/env python3
"""Semantic routing holdouts for the Legacy-restored ImprovementCore candidate.

The semantic frontiers were generated by the active reasoning model from real project
evidence, without a user-authored tool sequence. This runner tests whether the restored
controller routes those frontiers correctly under the full modern-guard wrapper.

This is not independent-agent replication. Source evidence is replayed into the
controller as semantic evidence, with explicit execution-truth labeling.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/"runtime"))

from improvement_core_knowledge_ledger import KnowledgeLedger
from improvement_core_legacy_restored import run_improvement_core_legacy_restored

PACKET=ROOT/"integration/IMPROVECORE_LEGACY_SEMANTIC_HOLDOUT_PACKET_132.json"


def load_packet():
    return json.loads(PACKET.read_text(encoding="utf-8"))


def initial_state(case):
    phase=case["phases"][0]
    state={
        "terminal":"CONTINUE",
        "admitted_continuation":True,
        "semantic_phase":0,
        "required_jobs":list(case.get("required_jobs",())),
        "work_items":list(phase.get("work_items",())),
        "semantic_holdout_id":case["id"],
        "semantic_domain":case["domain"],
        "source_evidence":list(case.get("evidence_state",())),
    }
    state.update(dict(case.get("initial_flags",{})))
    return state


def run_case(case):
    phases=list(case["phases"])
    executed=[]

    def phase_for(state):
        idx=int(state.get("semantic_phase",0))
        if idx>=len(phases):
            return None
        return phases[idx]

    def generate_questions(state,memory):
        phase=phase_for(state)
        if phase is None or state.get("terminal") in {"COMPLETE","OPEN","BLOCKED","CONFLICT"}:
            return []
        q=dict(phase["question"])
        q.setdefault("obligations",list(case.get("required_jobs",())))
        return [q]

    def generate_work(questions,state,memory):
        phase=phase_for(state)
        if phase is None:
            return []
        # This holdout replays semantic evidence; it does not mutate target
        # reality. Bind the replay jobs explicitly to the current execution
        # admission contract rather than letting a legacy fixture fail open
        # merely because it predates operation/effect typing.
        work=[]
        for row in phase["work_items"]:
            item=dict(row)
            item.setdefault("operation_class","VERIFY")
            item.setdefault("execution_effect_class","EVIDENCE_ONLY")
            work.append(item)
        return work

    def execute_work(selected,state,memory):
        phase=phase_for(state)
        selected_ids=[str(x["id"]) for x in selected]
        executed.append(selected_ids)
        return [{
            "status":"EXECUTED",
            "execution_truth":"SEMANTIC_EVIDENCE_REPLAY",
            "selected":selected_ids,
            "source_provenance":case.get("provenance",()),
            "result":dict(phase.get("result",{})) if phase else {},
        }]

    def admit_results(results,state,memory):
        phase=phase_for(state)
        result=dict(phase.get("result",{})) if phase else {}
        delta={
            "material_result_delta":bool(result.get("material_result_delta",True)),
            "evidence_refs":tuple(
                f"{row.get('surface')}:{row.get('file_id')}:{row.get('name')}"
                for row in case.get("provenance",())
            ),
            "semantic_holdout_result":result.get("statement",""),
        }
        if result.get("changed_representation"):
            delta["changed_representation"]=True
        return delta

    def update_state(state,memory,delta):
        nxt=dict(state)
        idx=int(nxt.get("semantic_phase",0))+1
        nxt["semantic_phase"]=idx
        if idx>=len(phases):
            nxt["terminal"]="COMPLETE"
            nxt["admitted_continuation"]=False
            nxt["semantic_result"]=delta.get("semantic_holdout_result")
        else:
            nxt["work_items"]=list(phases[idx]["work_items"])
            nxt["terminal"]="CONTINUE"
            nxt["admitted_continuation"]=True
        return nxt,dict(memory)

    def verify_return(state,memory,context):
        idx=int(state.get("semantic_phase",0))
        if idx<len(phases):
            return {
                "disposition":"CONTINUE",
                "goal_closed":False,
                "owned_work_remaining":True,
                "consequence_closed":True,
                "evidence":[f"semantic-holdout:{case['id']}:phase:{idx}:remaining"],
            }
        status=str(context.get("candidate_status","OPEN"))
        return {
            "disposition":"RETURN",
            "terminal":status,
            "goal_closed":status=="COMPLETE",
            "owned_work_remaining":False,
            "consequence_closed":True,
            "blocker":context.get("candidate_blocker"),
            "evidence":[f"semantic-holdout:{case['id']}:whole-job-closed"],
        }

    out=run_improvement_core_legacy_restored(
        "ImproveCore, independently determine the next useful work from this project evidence",
        target=f"semantic-holdout:{case['id']}",
        job="advance the live project without a user-specified tool sequence",
        basis="HOST_MODEL_SUPPLIED_SEMANTIC_FRONTIER+PROJECT_EVIDENCE",
        state=initial_state(case),
        memory={},
        generate_questions=generate_questions,
        generate_work=generate_work,
        execute_work=execute_work,
        admit_results=admit_results,
        update_state=update_state,
        knowledge_ledger=KnowledgeLedger(),
        hf2_enabled=True,
        hf2_max_rounds=4,
        max_iterations=8,
        return_verifier=verify_return,
        parent_max_rounds=8,
    )

    selected=[]
    for trace in out.candidate_traces:
        rows=trace.get("selected",())
        selected.extend(str(row.get("id")) for row in rows if isinstance(row,dict))
    expected=[
        str(x)
        for phase in phases
        for x in phase.get("expected_selected",())
    ]
    pass_selection=selected==expected
    passed=(
        out.status=="COMPLETE"
        and out.hf2_status=="RELATIVE_CLOSE"
        and pass_selection
        and bool(out.entry_receipt)
    )
    return {
        "id":case["id"],
        "domain":case["domain"],
        "status":out.status,
        "blocker":out.blocker,
        "hf2_status":out.hf2_status,
        "hf2_trace":out.hf2_trace,
        "entry_receipt":out.entry_receipt,
        "selected":selected,
        "expected_selected":expected,
        "selection_match":pass_selection,
        "execution_truth":"SEMANTIC_EVIDENCE_REPLAY",
        "knowledge_nodes":len(out.knowledge_summary),
        "source_provenance":case.get("provenance",()),
        "pass":passed,
    }


def run(output):
    packet=load_packet()
    cases=[run_case(case) for case in packet["cases"]]
    pass_count=sum(1 for row in cases if row["pass"])
    all_pass=pass_count==len(cases)
    report={
        "schema_version":1,
        "packet_id":packet["object_id"],
        "packet_status":packet["status"],
        "evidence_class":"HOST_MODEL_SUPPLIED_SEMANTIC_FRONTIER+REPOSITORY_CONTROL_EXECUTION",
        "independent_replication":False,
        "user_tool_sequence_supplied":False,
        "cases":cases,
        "case_count":len(cases),
        "pass_count":pass_count,
        "semantic_routing_holdouts":"PASS" if all_pass else "FAIL",
        "additional_existing_evidence":packet.get("additional_existing_evidence"),
        "promotion_evidence_status":(
            "MULTI_DOMAIN_SEMANTIC_ROUTING_PASS_WITH_EXPLICIT_NONINDEPENDENT_EVIDENCE_CLASS"
            if all_pass else
            "SEMANTIC_ROUTING_FAILURE"
        ),
    }
    output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text(json.dumps(report,indent=2,sort_keys=True,default=str),encoding="utf-8")
    print(json.dumps(report,indent=2,sort_keys=True,default=str))
    if not all_pass:
        raise SystemExit(1)
    return report


def main():
    p=argparse.ArgumentParser()
    p.add_argument(
        "--output",
        default=str(ROOT/"runtime/state/improvecore-legacy-semantic-holdouts-132/report.json"),
    )
    args=p.parse_args()
    run(Path(args.output))


if __name__=="__main__":
    main()
